### ISSUE TITLE
Error running the demo

### ISSUE THREAD

**Issue by arnold-pinto** [nabil-mansouri/nativescript-nbmaterial#1]
1. Downloaded the code
2. Navigated to `~/downloads/nativescript-nbmaterial-master/_demo`
3. `tns run android`

Code compiles but app crashes immediately with the following error

`
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5447)
System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6165)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Module.bootstrapApp(Module.java:311)
System.err:     at com.tns.Runtime.run(Runtime.java:521)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5444)
System.err:     ... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     at com.tns.Module.bootstrapApp(Module.java:309)
System.err:     ... 12 more
ActivityManager: Process org.nbmaterial.demo (pid 24240) has died
ActivityManager: cleanUpApplicationRecord -- 24240
`

**Comment by traderdata** [comment]
same thing here

**Comment by nabil-mansouri** [comment]
Hi  guys! i fixed package.json and deps. It should work now. Please reopen the issue if not

**Comment by Xsmael** [comment]
Now getting this error....

```
Unable to apply changes on device: 6c6dc037d440. Error is: cp: no such file or directory: c:\nativescript\nativescript-nbmaterial\_demo\node_modules\tns-android\framework\libs.
Executing after-watch hook from c:\nativescript\nativescript-nbmaterial\_demo\hooks\after-watch\nativescript-dev-typescript.js
```
