### ISSUE TITLE
About Icon Magic

### ISSUE THREAD

**Issue by empirefox** [nabil-mansouri/nativescript-nbmaterial#3]
Hi @nabil-mansouri. All icons here are used like this below, but i cannot find the source of `dashboard`. What's the magic and where are the other names? Thank you!
```xml
<bnav:Icon text="dashboard"  />
```
```ts
export class Icon extends Label {}
```

**Comment by nabil-mansouri** [comment]
Hi @empirefox! All is done through CSS:
https://github.com/nabil-mansouri/nativescript-nbmaterial/blob/master/_demo/app/app.css

As you can see in this file, Icon component has font family value: material-icons

**Comment by empirefox** [comment]
The official [doc](https://docs.nativescript.org/ui/icon-fonts) says we should do it like `String.fromCharCode(0xe903)`. How does it work when the `dashboard` to char code mapping does not exist?

**Comment by empirefox** [comment]
OK, finally i googled `ligatures` feature of css3 font. So close the issue now.
